#!/bin/bash
read -p "Enter the password:" password
len="${#password}"
if [ $len -ge 8 ]
then
        echo "$password" | grep -q '[0-9]'
        if [ $? -eq 0 ]
        then
                echo "$password" | grep -q '[A-Z]'
                if [ $? -eq 0 ]
                then
                        echo "$password" | grep -q '[a-z]'
                        if [ $? -eq 0 ]
                        then
                                echo " strong password"
                        else
                                echo "password should contain small letters"
                        fi
                else
                        echo " password should contain capital letters"

                fi
        else
                echo "Password should contain numbers"
        fi
else
        echo "password length must be greater than 8"
fi
