#!/bin/bash
read -p "Enter a number to find factorial" num
n=$num
if [[ $num -eq 0 || $num -eq 1 ]]
then
        echo "factorial is 1"
elif [ $num -lt 0 ]
then
        echo "Invalid number"
else
        fact=1
        while [ $num -gt 0 ]
        do
                fact=$((fact*num))
                num=$((num - 1))

        done
        echo "Factorial is $fact"
fi
