#!/bin/bash
echo "Enter two numbers: "
read a b
sum=`expr $a + $b`
diff=`expr $a - $b`
mul=`expr $a "*" $b`
div=`expr $a / $b`
mod=`expr $a % $b`
echo "Sum = $sum"
echo "Difference = $diff"
echo "Product = $mul"
echo "Division = $div"
echo "Remainder = $mod"
