#!/bin/bash
echo "Enter the username"
read usr
echo "Enter password:"
read pass
usrname='admin'
password='admin123'
if [[ $usr -eq $usrname && $pass -eq $password ]]
then
        echo "Welcome"
else
        echo "Invalid username or password"
fi
