#!/bin/bash
read -p "Enter filename:" file
w=$(cat "$file" | wc -w)
c=$(cat "$file" | wc -c)
l=$(grep -c "." "$file")
s=$(cat "$file" | wc -l)
echo "word count $w"
echo "character count: $c"
echo "number of lines: $l,$s"
